services:
  prometheus:
    image: prom/prometheus:latest
    container_name: logops-prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped
    depends_on:
      - alertmanager

  promtail:
    image: grafana/promtail:2.9.0
    container_name: logops-promtail
    command: ["-config.file=/etc/promtail/promtail-config.yml"]
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - promtail-tmp:/tmp
      # względem repo root:
      - ../../../data/ingest:/var/log/logops:ro
      # NOWE: przenieśliśmy mounty poza /var/log/logops (bo to RO)
      - ../../../logs:/var/log/logops-hosts/logs:ro
      - ../../../data/orch/scenarios:/var/log/logops-hosts/scenarios:ro
    restart: unless-stopped
    depends_on:
      - loki

  alertmanager:
    image: prom/alertmanager:latest
    container_name: logops-alertmanager
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --cluster.advertise-address=0.0.0.0:9094
      - --log.level=debug
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.0
    container_name: logops-loki
    command: ["-config.file=/etc/loki/loki-config.yml"]
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki-data:/loki
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: logops-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
      - GF_PLUGIN_BGDOWNLOADER_ENABLED=false
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - prometheus
      - loki

volumes:
  grafana-data:
  loki-data:
  promtail-tmp:
  prometheus-data:
