global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'logops-ingest'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'logops-authgw'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: 'logops-core'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8095']

  - job_name: 'logops-orchestrator'
    static_configs:
      - targets: ['host.docker.internal:8070']
#  - job_name: dummy_down
#    static_configs:
#      - targets: ["127.0.0.1:65535"]   # port nieuÅ¼ywany => stale DOWN
