services:
  loki:
    image: grafana/loki:2.9.6
    container_name: logops-loki
    command: -config.file=/etc/loki/config.yml
    ports: ["3100:3100"]
    volumes:
      - ./loki/loki-config.yml:/etc/loki/config.yml:ro
      - loki-data:/loki
    networks: [obs]

  promtail:
    image: grafana/promtail:2.9.6
    container_name: logops-promtail
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml:ro
      - ../../data/ingest:/var/logops/data/ingest:ro
      - promtail-data:/var/lib/promtail
    depends_on: [loki]
    networks: [obs]

  alertmanager:
    image: prom/alertmanager:v0.28.1
    container_name: logops-alertmanager
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/alertmanager
    ports: ["9093:9093"]
    # MONTUJEMY *KATALOG* rendered, w kt√≥rym jest PLIK alertmanager.yml
    volumes:
      - ./alertmanager/rendered:/etc/alertmanager:ro
    networks: [obs]
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.54.0
    container_name: logops-prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    ports: ["9090:9090"]
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
      - prometheus-data:/prometheus
    depends_on: [alertmanager]
    networks: [obs]

  grafana:
    image: grafana/grafana:10.4.0
    container_name: logops-grafana
    ports: ["3000:3000"]
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
    depends_on: [loki, prometheus]
    networks: [obs]

volumes:
  loki-data:
  promtail-data:
  prometheus-data:
  grafana-data:

networks:
  obs:
