global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'logops-gateway'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'logops_ingest'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'logops_authgw'
    static_configs:
      - targets: ['host.docker.internal:8090']
